#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top38
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.m39
    set site_3_0 $base.m39
    set site_4_0 .top38.tNo46.t0 
    set site_4_0 $site_4_0
    set site_5_0 $site_4_0.tLa54
    set site_4_1 .top38.tNo46.t1 
    set site_4_2 .top38.tNo46.pg0 
    set site_4_0 $site_4_2
    set site_5_0 $site_4_0.scr57

    #Updating ttreeview attributes
    .top38.tNo46.pg0.scr57.01 configure\
        -height  4

    #heading options.
    .top38.tNo46.pg0.scr57.01 heading #0 \
             -text "Options" \
             -anchor center \
             -command advancedselect
    #column options.
    .top38.tNo46.pg0.scr57.01 column #0 \
             -width 964 \
             -minwidth 20 \
             -stretch 1 \
             -anchor w
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top38 {base} {
    if {$base == ""} {
        set base .top38
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m39" -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 1000x700+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2872 1548
    wm minsize $top 500 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "RxEditor"
    vTcl:DefineAlias "$top" "maingui" vTcl:Toplevel:WidgetProc "" 1
    menu $top.m39 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $top.m39 add cascade \
        -menu "$top.m39.men40" -activebackground {#d9d9d9} \
        -activeforeground {#000000} -accelerator f -background {#d9d9d9} \
        -font TkMenuFont -foreground {#000000} -label File 
    set site_3_0 $top.m39
    menu $site_3_0.men40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men40 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -accelerator o -background {#d9d9d9} -command {# TODO} \
        -font TkMenuFont -foreground {#000000} -label Open... 
    $site_3_0.men40 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -accelerator s -background {#d9d9d9} -command {# TODO} \
        -font TkMenuFont -foreground {#000000} -label Save 
    $site_3_0.men40 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -accelerator a -background {#d9d9d9} -command {# TODO} \
        -font TkMenuFont -foreground {#000000} -label SaveAs... 
    $site_3_0.men40 add separator \
        -background {#d9d9d9} 
    $site_3_0.men40 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -accelerator x -background {#d9d9d9} -command {# TODO} \
        -font TkMenuFont -foreground {#000000} -label Exit 
    $top.m39 add cascade \
        -menu "$top.m39.men41" -activebackground {#d9d9d9} \
        -activeforeground {#000000} -accelerator v -background {#d9d9d9} \
        -font TkMenuFont -foreground {#000000} -label View 
    set site_3_0 $top.m39
    menu $site_3_0.men41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men41 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -accelerator b -background {#d9d9d9} -command {# TODO} \
        -font TkMenuFont -foreground {#000000} -label {Basic View} 
    $site_3_0.men41 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -accelerator d -background {#d9d9d9} -command {# TODO} \
        -font TkMenuFont -foreground {#000000} -label {Advanced View} 
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo46 \
        -width 300 -height 200 -takefocus {} 
    vTcl:DefineAlias "$top.tNo46" "notebook" vTcl:WidgetProc "maingui" 1
    frame $top.tNo46.t0 \
        -background {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor {#c0c0c0} 
    vTcl:DefineAlias "$top.tNo46.t0" "notebook_basic" vTcl:WidgetProc "maingui" 1
    $top.tNo46 add .top38.tNo46.t0 \
        -padding 0 -sticky nsew -state normal -text Safe -image {} \
        -compound none -underline -1 
    set site_4_0  $top.tNo46.t0
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $site_4_0.tLa54 \
        -text SAFE(tm) -borderwidth 2 -relief sunken -width 220 -height 105 
    vTcl:DefineAlias "$site_4_0.tLa54" "safe" vTcl:WidgetProc "maingui" 1
    set site_5_0 $site_4_0.tLa54
    ttk::style configure TRadiobutton -background #d9d9d9
    ttk::style configure TRadiobutton -foreground #000000
    ttk::style configure TRadiobutton -font TkDefaultFont
    ttk::radiobutton $site_5_0.tRa55 \
        -variable safemodeon -takefocus {} -text On 
    vTcl:DefineAlias "$site_5_0.tRa55" "safeOn" vTcl:WidgetProc "maingui" 1
    ttk::style configure TRadiobutton -background #d9d9d9
    ttk::style configure TRadiobutton -foreground #000000
    ttk::style configure TRadiobutton -font TkDefaultFont
    ttk::radiobutton $site_5_0.tRa56 \
        -variable safemodeoff -takefocus {} -text Off 
    vTcl:DefineAlias "$site_5_0.tRa56" "safeOff" vTcl:WidgetProc "maingui" 1
    place $site_5_0.tRa55 \
        -in $site_5_0 -x 20 -y 30 -anchor nw -bordermode ignore 
    place $site_5_0.tRa56 \
        -in $site_5_0 -x 20 -y 60 -anchor nw -bordermode ignore 
    place $site_4_0.tLa54 \
        -in $site_4_0 -x 10 -y 10 -width 220 -relwidth 0 -height 105 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.tNo46.t1 \
        -background {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo46.t1" "notebook_t2" vTcl:WidgetProc "maingui" 1
    $top.tNo46 add .top38.tNo46.t1 \
        -padding 0 -sticky nsew -state normal -text Mixes -image {} \
        -compound none -underline -1 
    set site_4_1  $top.tNo46.t1
    frame $top.tNo46.pg0 \
        -background {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo46.pg0" "notebook_t2" vTcl:WidgetProc "maingui" 1
    $top.tNo46 add .top38.tNo46.pg0 \
        -padding 0 -sticky nsew -state normal -text Advanced -image {} \
        -compound none -underline -1 
    set site_4_2  $top.tNo46.pg0
    ttk::style configure Treeview.Heading -background #d9d9d9
    ttk::style configure Treeview.Heading -font TkDefaultFont
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_2.scr57 \
        -relief groove -background {#d9d9d9} -height 15 \
        -highlightbackground {#d9d9d9} -highlightcolor black -padx 2 -pady 2 \
        -width 30 
    vTcl:DefineAlias "$site_4_2.scr57" "advancedtree" vTcl:WidgetProc "maingui" 1
    place $site_4_2.scr57 \
        -in $site_4_2 -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo46 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top38

