#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Oct 28, 2017 12:01:46 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

from page import RxEditor

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    rxeditor = RxEditor.RxEditor(root)
    rxeditor.draw()
    root.mainloop()

'''
w = None
def create_RxEditor(root, *args, **kwargs):
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    gui_support.set_Tk_var()
    top = RxEditor (w)
    gui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_RxEditor():
    global w
    w.destroy()
    w = None
'''

if __name__ == '__main__':
    vp_start_gui()
