#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Oct 28, 2017 11:42:35 AM


import json
import traceback
import rxgui
import rxfile

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    from tkinter import filedialog
    py3 = 1

def set_Tk_var():
    global safemode
    global filterstring
    global safelimitedflightmodeenabled
    global defaultsafelimitedflightmode
    global safelimitedflightmodeswitchvalue
    global safeinfolabel
    safemode = IntVar()
    safelimitedflightmodeenabled = IntVar()
    defaultsafelimitedflightmode = IntVar()
    safelimitedflightmodeswitchvalue = StringVar()
    filterstring = StringVar()
    safeinfolabel = StringVar('')

def menu_open():
    global w
    global safemode
    global safelimitedflightmodeenabled
    global defaultsafelimitedflightmode
    global safelimitedflightmodeswitchvalue
    global safeinfolabel
    options = {}
    options['title'] = "Open Rx SRM..."
    options['filetypes'] = [('srm', '*.srm'), ('any', '*.*')]
    filename = filedialog.askopenfile(mode="r", **options)
    if filename is not None:
        print(filename.name)
        try:
            fh = rxfile.RxFileHandler.RxFileWrapper(filename.name)
            rxgui.rxeditorstate.setFileHandle(fh)
            rxgui.PopulateSettings.clear(w.getAdvancedTree())
            rxgui.PopulateSettings.populateAdvancedTree(fh, w.getAdvancedTree())
            filterstring.set('')
            rxgui.PopulateSettings.populateSafeTab(fh,
                                                   {"safemode":safemode,
                                                    "safelimitedflightmodeenabled":safelimitedflightmodeenabled,
                                                    "defaultsafelimitedflightmode":defaultsafelimitedflightmode,
                                                    "safelimitedflightmodeswitchvalue":safelimitedflightmodeswitchvalue,
                                                    "safeinfolabel": safeinfolabel})
        except:
            traceback.print_exc()

def menu_save():
    fh = rxgui.rxeditorstate.getFileHandle()
    if fh is not None:
        fh.save()

def menu_saveAs():
    fh = rxgui.rxeditorstate.getFileHandle()
    if fh is not None:
        options = {}
        options['title'] = "Save Rx SRM..."
        options['filetypes'] = [('srm', '*.srm'), ('any', '*.*')]
        options['defaultextension'] = '.srm'
        filename = filedialog.asksaveasfile(mode="w", **options)
        if filename is not None:
            fh.saveAs(filename.name)

def menu_exit():
    fh = rxgui.rxeditorstate.getFileHandle()
    if fh is not None and fh.isDirty():
        menu_saveAs()
    destroy_window()

def tree_doubleclick(event):
    global w
    item = w.getAdvancedTree().selection()[0]
    keys = item.split('-')
    values = w.getAdvancedTree().item(item)["values"]
    if len(values) > 0:
        # We have a value - prevents an error from clicking parent elements in the tree
        value = values[0]
        if isinstance(value,str) and value.startswith('['):
            # Value is really a list
            value = json.loads(value)
        elif isinstance(value,str) and value.startswith('0x'):
            # Value in hex
            pass
        else:
            try:
                value = int(value)
            except ValueError:
                # Just go with a string
                pass

        return item, keys, value, rxgui.rxeditorstate.getFileHandle()

def tree_updatevalues(item, keys, newvalues, fh):
    global w

    w.getAdvancedTree().item(item, values=[str(newvalues)])
    fh.setValue(keys, newvalues)

def filterStringChange():
    global filterstring
    if len(filterstring.get()) > 0:
        fh = rxgui.rxeditorstate.getFileHandle()
        rxgui.PopulateSettings.clear(w.getAdvancedTree())
        rxgui.PopulateSettings.populateAdvancedTreeFiltered(fh, w.getAdvancedTree(), filterstring.get().lower())
    else:
        fh = rxgui.rxeditorstate.getFileHandle()
        rxgui.PopulateSettings.clear(w.getAdvancedTree())
        rxgui.PopulateSettings.populateAdvancedTree(fh, w.getAdvancedTree())

def safeModeChange():
    global safemode
    fh = rxgui.rxeditorstate.getFileHandle()
    if fh is not None:
        fh.setValue(["data","autopilot","safeEnabled"], safemode.get())
        filterStringChange()

def safeLimitedFlightModeEnabledChange():
    global safelimitedflightmodeenabled
    fh = rxgui.rxeditorstate.getFileHandle()
    if fh is not None:
        fh.setValue(["data","system","safeLimitedFlightModesDisabled"], safelimitedflightmodeenabled.get())
        filterStringChange()

def defaultSafeLimitedFlightModeChange():
    global defaultsafelimitedflightmode
    fh = rxgui.rxeditorstate.getFileHandle()
    if fh is not None:
        fh.setValue(["data","system","defaultSafeLimitedFlightMode"], defaultsafelimitedflightmode.get())
        filterStringChange()

def safeLimitedFlightModeSwitchValueChange():
    global safelimitedflightmodeswitchvalue
    global safeinfolabel
    # Validate the value
    try:
        intval = int(safelimitedflightmodeswitchvalue.get())
        if intval <= 255 and intval >= 0:
            fh = rxgui.rxeditorstate.getFileHandle()
            if fh is not None:
                fh.setValue(["data","system","safeLimitedFlightModeSwitch"], intval)
                filterStringChange()
        else:
            safeinfolabel.set("Error: Valu emust be an integer between 0 and 255.")
    except:
        safeinfolabel.set("Error: Valu emust be an integer between 0 and 255.")

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import gui
    gui.vp_start_gui()


